package db

import (
	"context"

	petapisv1 "buf.build/gen/go/wgeorgecook/go-app-example/protocolbuffers/go/wgeorgecook/petapis/v1"
	"github.com/jackc/pgx/v5"
)

// Connect instantiates a *pgx.Connection and returns
// that connection or the error it throws. Caller is
// responsible for closing the returned connection
// when it is unused.
func Connect(dbUri string) (*pgx.Conn, error) {
	return pgx.Connect(context.Background(), dbUri)
}

// Query uses the provided connection to run the
// query generated by the input petapisv1.Query and
// returns either a slice of Pet or an error.
func Query(conn *pgx.Conn, queryFields []petapisv1.Query) ([]Pet, error) {
	return getAllPets(conn)
}
