services:
  data-access:
    build: 
      context: ./data-access/
      dockerfile: ./build/Dockerfile
    image: williamcook/go-example-app:data-access-${TAG_VERSION}
    ports:
      - "8088:8088"
    environment:
    - MIGRATION_DIRECTION=${MIGRATION_DIRECTION}
  postgres:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ${PWD}/pg-data/:/var/lib/postgresql/data/
    